import { Repository } from '../Types/DataTypes';
import { GraphQLResponse } from '../Types/ResponseTypes';

export const mockUrls = [
    'https://github.com/Cinnamon/kotaemon',
    'https://github.com/Z4nzu/hackingtool',
    'https://github.com/mendableai/firecrawl',
    'https://github.com/cemu-project/Cemu',
    'https://github.com/dokku/dokku',
    'https://github.com/x/someunkonwrepo',
    'https://www.npmjs.com/package/react',
    'https://www.npmjs.com/package/@google-cloud/firestore',
    'https://www.npmjs.com/package/@launchdarkly/node-server-sdk',
    'https://www.npmjs.com/package/@digest/eslint-config-typescript',
    'https://www.npmjs.com/package/@applicaster/zapp-react-native-bridge',
];

export const mockRepos: Repository<any>[] = [
    {
        owner: 'Cinnamon',
        repoName: 'kotaemon',
        fileUrl: 'https://github.com/Cinnamon/kotaemon',
        queryResult: null,
        NDJSONRow: {
            URL: 'https://github.com/Cinnamon/kotaemon',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'Z4nzu',
        repoName: 'hackingtool',
        fileUrl: 'https://github.com/Z4nzu/hackingtool',
        queryResult: null,
        NDJSONRow: {
            URL: 'https://github.com/Z4nzu/hackingtool',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'mendableai',
        repoName: 'firecrawl',
        fileUrl: 'https://github.com/mendableai/firecrawl',
        queryResult: null,
        NDJSONRow: {
            URL: 'https://github.com/mendableai/firecrawl',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'cemu-project',
        repoName: 'Cemu',
        fileUrl: 'https://github.com/cemu-project/Cemu',
        queryResult: null,
        NDJSONRow: {
            URL: 'https://github.com/cemu-project/Cemu',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'dokku',
        repoName: 'dokku',
        fileUrl: 'https://github.com/dokku/dokku',
        queryResult: null,
        NDJSONRow: {
            URL: 'https://github.com/dokku/dokku',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'x',
        repoName: 'someunkonwrepo',
        fileUrl: 'https://github.com/x/someunkonwrepo',
        queryResult: null,
        NDJSONRow: {
            URL: 'https://github.com/x/someunkonwrepo',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
];

export const mockValidRepos: Repository<any>[] = [
    {
        owner: 'Cinnamon',
        repoName: 'kotaemon',
        fileUrl: 'https://github.com/Cinnamon/kotaemon',
        queryResult: {
            description: 'An open-source RAG-based tool for chatting with your documents.',
            name: 'kotaemon',
            url: 'https://github.com/Cinnamon/kotaemon',
            owner: {
                login: 'Cinnamon',
            },
        },
        NDJSONRow: {
            URL: 'https://github.com/Cinnamon/kotaemon',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'Z4nzu',
        repoName: 'hackingtool',
        fileUrl: 'https://github.com/Z4nzu/hackingtool',
        queryResult: {
            description: 'ALL IN ONE Hacking Tool For Hackers',
            name: 'hackingtool',
            url: 'https://github.com/Z4nzu/hackingtool',
            owner: {
                login: 'Z4nzu',
            },
        },
        NDJSONRow: {
            URL: 'https://github.com/Z4nzu/hackingtool',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'mendableai',
        repoName: 'firecrawl',
        fileUrl: 'https://github.com/mendableai/firecrawl',
        queryResult: {
            description:
                '🔥 Turn entire websites into LLM-ready markdown or structured data. Scrape, crawl and extract with a single API.',
            name: 'firecrawl',
            url: 'https://github.com/mendableai/firecrawl',
            owner: {
                login: 'mendableai',
            },
        },
        NDJSONRow: {
            URL: 'https://github.com/mendableai/firecrawl',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'cemu-project',
        repoName: 'Cemu',
        fileUrl: 'https://github.com/cemu-project/Cemu',
        queryResult: {
            description: 'Cemu - Wii U emulator',
            name: 'Cemu',
            url: 'https://github.com/cemu-project/Cemu',
            owner: {
                login: 'cemu-project',
            },
        },
        NDJSONRow: {
            URL: 'https://github.com/cemu-project/Cemu',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
    {
        owner: 'dokku',
        repoName: 'dokku',
        fileUrl: 'https://github.com/dokku/dokku',
        queryResult: {
            description:
                'A docker-powered PaaS that helps you build and manage the lifecycle of applications',
            name: 'dokku',
            url: 'https://github.com/dokku/dokku',
            owner: {
                login: 'dokku',
            },
        },
        NDJSONRow: {
            URL: 'https://github.com/dokku/dokku',
            NetScore: 0,
            NetScore_Latency: 0,
            RampUp: 0,
            RampUp_Latency: 0,
            Correctness: 0,
            Correctness_Latency: 0,
            BusFactor: 0,
            BusFactor_Latency: 0,
            ResponsiveMaintainer: 0,
            ResponsiveMaintainer_Latency: 0,
            License: 0,
            License_Latency: 0,
        },
    },
];

export const mockGQLResult: GraphQLResponse<any> = {
    data: {
        repo0: {
            description: 'An open-source RAG-based tool for chatting with your documents.',
            name: 'kotaemon',
            url: 'https://github.com/Cinnamon/kotaemon',
            owner: {
                login: 'Cinnamon',
            },
        },
        repo1: {
            description: 'ALL IN ONE Hacking Tool For Hackers',
            name: 'hackingtool',
            url: 'https://github.com/Z4nzu/hackingtool',
            owner: {
                login: 'Z4nzu',
            },
        },
        repo2: {
            description:
                '🔥 Turn entire websites into LLM-ready markdown or structured data. Scrape, crawl and extract with a single API.',
            name: 'firecrawl',
            url: 'https://github.com/mendableai/firecrawl',
            owner: {
                login: 'mendableai',
            },
        },
        repo3: {
            description: 'Cemu - Wii U emulator',
            name: 'Cemu',
            url: 'https://github.com/cemu-project/Cemu',
            owner: {
                login: 'cemu-project',
            },
        },
        repo4: {
            description:
                'A docker-powered PaaS that helps you build and manage the lifecycle of applications',
            name: 'dokku',
            url: 'https://github.com/dokku/dokku',
            owner: {
                login: 'dokku',
            },
        },
        repo5: null,
    },
    errors: [
        {
            type: 'NOT_FOUND',
            path: [],
            locations: [],
            message: "Could not resolve to a Repository with the name 'x/someunkonwrepo'.",
        },
    ],
};
